### PR TITLE
Moving to ES2015

### LINKED ISSUE #14: Accessor method signature has been changed in v4
The accessors are now supplied with `(d, i, nodes)` not sure about context. Many of the accessors are currently broken anyway because they're using fat-arrow + `this`.

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Also fixes the issues with accessors / D3v4 

closes #14 

- [x] mark as a breaking change
- [x] ES2015-ify `demo.js`
- [x] fix the unit tests!
- [x] explore d3-array `scan` (postponing until after the refactor which is on its way)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
-export { default as label } from './src/label';
-export { default as textLabel } from './src/textLabel';
-export { default as greedy } from './src/greedy';
-export { default as annealing } from './src/annealing';
-export { default as removeOverlaps } from './src/removeOverlaps';
-export { default as boundingBox } from './src/boundingBox';
-export { default as intersect } from './src/intersect';
+export { default as layoutLabel } from './src/label';
```
Comment (chrisprice) [inline index.js]: I think the build's failing because you've renamed this here but not in the bundleSpec?

Comment (chrisprice) [inline index.js]: Also that probably makes all of these breaking changes?

File: site/demo.js [hunk 2]
```diff
@@ -2,27 +2,27 @@ import { range, sum } from 'd3-array';
...
 var data = [];
 
 // we intercept the strategy in order to capture the final layout and compute statistics
 function strategyInterceptor(strategy) {
     var interceptor = function(layout) {
-        var start = new Date().getMilliseconds();
+        var start = new Date().getTime();
         var finalLayout = strategy(layout);
-        var time = new Date().getMilliseconds() - start;
+        var time = new Date().getTime() - start;
```
Comment (chrisprice) [inline site/demo.js]: /aisde - you can actually directly subtract dates from each other (because the `-` operator needs numbers, it'll call `valueOf` which is equivalent to `getTime`.

File: site/demo.js [hunk 3]
```diff
@@ -69,15 +69,13 @@ function render() {
...
-        });
+        .attr('r', 2)
+        .attr('cx', d => d.x)
+        .attr('cy', d => d.y);
 
-    var labels = labelLayout(strategy)
-        .size(function() {
-            var textSize = select(this)
+    var labels = layoutLabel(strategy)
+        .size(function(d, i, g) {
```
Comment (chrisprice) [inline site/demo.js]: function?

File: site/demo.js [hunk 4]
```diff
@@ -2,27 +2,27 @@ import { range, sum } from 'd3-array';
 import { rebind } from 'd3fc-rebind';
 import { select, selectAll } from 'd3-selection';
 import * as d3 from 'd3-selection';
-import { label as labelLayout, textLabel, annealing, intersect } from '..';
+import { layoutLabel, layoutTextLabel, layoutAnnealing, layoutIntersect, layoutRemoveOverlaps } from '..';
 import * as fc from '..';
 
 var labelPadding = 4;
```
Comment (chrisprice) [inline site/demo.js]: vars?

File: site/demo.js (hunk 3 above)
Comment (chrisprice) [inline site/demo.js]: I think there's a few more in this file but I can't comment on the lines

File: src/annealing.js [hunk 5]
```diff
@@ -61,25 +61,25 @@ export default () => {
...
         return collisionArea + areaOutsideContainer + orientationBias;
-    }
+    };
 
-    var strategy = (data) => {
+    const strategy = (data) => {
 
-        var originalData = data;
-        var iteratedData = data;
+        const originalData = data;
```
Comment (chrisprice) [inline src/annealing.js]: Call the argument `originalData`?

File: site/demo.js (hunk 3 above)
Comment (ColinEberhardt) [inline site/demo.js]: Ah, looks like I completely missed `demo.js` when cleaning up

File: site/demo.js (hunk 2 above)
Comment (ColinEberhardt) [inline site/demo.js]: Good point, forgot you can simply subtract dates

File: src/util/minimum.js [hunk 6]
```diff
@@ -1,8 +1,6 @@
 // searches for a minimum when applying the given accessor to each item within the supplied array.
 // The returned array has the following form:
 // [minumum accessor value, datum, index]
-export default (data, accessor) => data.map((dataPoint, index) => {
-    return [accessor(dataPoint, index), dataPoint, index];
-}).reduce((accumulator, dataPoint) => {
-    return accumulator[0] > dataPoint[0] ? dataPoint : accumulator;
-}, [Number.MAX_VALUE, null, -1]);
+export default (data, accessor) =>
```
Comment (chrisprice) [inline src/util/minimum.js]: Might scan replace this?

> This function is similar to min, except it allows the use of a comparator rather than an accessor and it returns the index instead of the accessed value. See also bisect.

https://github.com/d3/d3-array#scan

File: src/annealing.js (hunk 5 above)
Comment (ColinEberhardt) [inline src/annealing.js]: I'll resolve this in a future PR, big refactor coming
